### ISSUE TITLE
Faded Content still touchable

### ISSUE THREAD

**Issue by KBLNY** [franfran/react-native-fade-toogle#1]
Hi, Thanks a lot for your work.
I have a FadeToggle component including touchable text.
However, when I toggle (hide) the component, which actually perform very well, I am still able to tap my touchable text while it is no longer present on the screen.
Is there any trick here?
Thanks

Here is my code for reference:

```
<FadeToogle ref="emotionsFader" component="View" easing={Easing.linear()} duration={1000} callback={ () => {} } style={style.emotionsContainer} >
   <TouchableOpacity ref="likePostButton" style={style.likePostButtonTouch} onPress={() => this.likePost()}>
      <Text style={style.likePostButtonText}> Like this post </Text>
   </TouchableOpacity>
<FadeToogle>
```

**Comment by franfran** [comment]
Thanks for the feedback.

The idea of FadeToggle is supporting fade in/out with a value, but not necessary always 1 and 0.
The component itself support:

```
fromOpacity: PropTypes.number,
toOpacity: PropTypes.number,
```

So actually it is possible to do 
`<FadeToggle fromOpacity="1" toOpacity="0.5">
`
The component is now half-way "invisible" doesn't means it does not exist.

If in your project, completely "invisible" means "lost in space" and you shouldn't click on it, then I suggest you do this.

Add a listener to your likePostButton, when click on it, check the state of FadeToggle.

```
if (likePostButtonClicked && this.refs.fade.state.opacity == 0){
  //I am invisible and I won't response
}

```

Hope it helps and good luck.

**Comment by KBLNY** [comment]
Thanks for your reply.
I first opted for a non-zero opacity, like you suggest.
I thought the same approach as you concerning the "invisible" way, but I was wondering if this would be part of future releases?
Thanks a lot

**Comment by franfran** [comment]
I see what you mean.  So if that is part of the core function, then whoever implement it no need to do this checking manually.

I will put that in future release.

**Comment by KBLNY** [comment]
I just submit a PR by adding an optional `isDisabled` property
