### ISSUE TITLE
callback props doc is wrong

### ISSUE THREAD

**Issue by KBLNY** [franfran/react-native-fade-toogle#2]
Hi thanks a lot for the project,

There is a issue with the `callback`property.
In the doc `callback`is not required, however, if I do not provide it, I got an error.

So, please update the README stating `callback`is required or please update your code by checking if the `this.props.callback !== undefined`.

What do you think? Based on your response, I'm going to submit a PR.

Kevin

**Comment by franfran** [comment]
Yes, pls do a PR.  Thanks for helping out.

**Comment by KBLNY** [comment]
Well, in fact your documentation and your code are in line, both telling the `callback` is optional 👍 
However, your `npm` is not updated.
Please do a `npm publish` 👍

**Comment by franfran** [comment]
thx @KBLNY the npm package updated as well.
